### ISSUE TITLE
yarn test fail: Manifest not found. Search paths used: polywrap.app.yaml, polywrap.app.yml

### ISSUE THREAD

**Issue by ivanceras** [polywrap/integrations#72]
After merging the build-fix PR, The `yarn rebuild` works without problem, however `yarn test` command doesn't work anymore.
```log
yarn test
yarn run v1.22.10
warning package.json: No license field
$ yarn test:e2e
warning package.json: No license field
$ yarn test:e2e:codegen && jest --passWithNoTests --runInBand --verbose
warning package.json: No license field
$ cd tests && npx polywrap app codegen -c wrap
Manifest not found. Search paths used: polywrap.app.yaml, polywrap.app.yml
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ivanceras** [comment]
I figured, I'd just rename `tests/web3api.app.yaml` to `tests/polywrap.app.yaml`,
but I got a new error message.
```shell
$yarn test
yarn run v1.22.10
warning package.json: No license field
$ yarn test:e2e
warning package.json: No license field
$ yarn test:e2e:codegen && jest --passWithNoTests --runInBand --verbose
warning package.json: No license field
$ cd tests && npx polywrap app codegen -c wrap
✔ Manifest loaded from ./polywrap.app.yaml
✔ Generate types
🔥 Code was generated successfully 🔥
ts-jest[ts-compiler] (WARN) tests/mutation.spec.ts:3:36 - error TS2307: Cannot find module '@web3api/client-js' or its corresponding type declarations.

3 import { Uri, Web3ApiClient } from "@web3api/client-js";
                                     ~~~~~~~~~~~~~~~~~~~~
tests/mutation.spec.ts:4:24 - error TS2307: Cannot find module '@web3api/test-env-js' or its corresponding type declarations.

4 import { runCLI } from "@web3api/test-env-js";
                         ~~~~~~~~~~~~~~~~~~~~~~
ts-jest[ts-compiler] (WARN) tests/w3/types.ts:8:8 - error TS2307: Cannot find module '@web3api/core-js' or its corresponding type declarations.

8 } from "@web3api/core-js";
         ~~~~~~~~~~~~~~~~~~
 FAIL  tests/mutation.spec.ts
  ● Test suite failed to run

    Cannot find module '@web3api/client-js' from 'tests/mutation.spec.ts'

      1 | import { Substrate_Mutation } from "./w3";
      2 |
    > 3 | import { Uri, Web3ApiClient } from "@web3api/client-js";
        | ^
      4 | import { runCLI } from "@web3api/test-env-js";
      5 | import path from "path";
      6 |

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (tests/mutation.spec.ts:3:1)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.049 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
